apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-connection
  namespace: admin-api
spec:
  encryptedData:
    db: AgAOZb4qwMvdYFMjnXRSzig9h4mRmyTkIlT620Fozu/qNqwPhT/pDhPn8XRJENycfuJj0/5KBW+C5J5brS3ihBRf5NzI12OFQRrThUy+Mcdo9GWiZbvMPM2BRketWN/iLvCx1b934kRX2DvJaDXcwNMHSkzr7CrQPzs18fOGTyko9+Y9B1Jf+rwP0oNKVMe0b7yQWxFs21KbfXCU7udp8BNDIMzjo61Vigfcq665nOfWa5U+M24OA5xgUnLXMFPAdhsh/4DPyDjk13Y3n1lMp9e7lyDpWZvLWeJSQxl9O2fY6iC6dHbB+kUAVoezh1dym4v24ytHHiGvt+pMWL2Y5jnktFBlM0CGznCnnGsZA7UeWR2KNzOWSEjCWlwy3XsRbA0YWjBmEIOVxlD5ZJHPZUE+GNp8KFDp2JjMdnSADcGdVOM1rauu2hew4qsFHHicSyz1ia7caXY7C2bMKXZatPg3CcnJgYizdNXjJBXpctJAt/NZ2ONkPeC09+XDAQDCiu4L9OupN+WiQTMJwFh820Ba4Stp5+T7OB/2nG2TJG7J27AyGEdJfoYH/bPfESW8TrR5THuyNuYjIJwBST5zBGzUHYvja8fBxjo499Vbuv7AMdxN0sn/l5UbpbpV6vRK3Lq6Ib7KUkEbZjTx7lQq5Z1JEXvSGiLy97tbfl05ttb5xKPs3YZ0acyN1SOV10F6Cdd54bxyB6TMFP0za/0Zvv9xb25HbgRkhVgpMWjlFWRAV2ZgQdEDQ7Y+KN9lAaYz+sDVd5BlxEsX1FNeLICFAjZijJI3sEhyuvPRHHGpphZ7ChicmfqddkAMQxDHCnB8NQ6yxhJDdSTp7yOTErPp7y2vekROEi72OcH+7nt0kl3/gcnSd/S1ilY=
  template:
    metadata:
      creationTimestamp: null
      name: database-connection
      namespace: admin-api

