bases:
  - ../../base
patchesStrategicMerge:
  - patch-enable-verify-publishing.yaml
  - treetracker-admin-api-mapping.yaml
  - database-connection-sealed-secret.yaml
  - treetracker-admin-api-jwt-sealed-secret.yaml
  - treetracker-dev-rabbitmq-sealedsecret.yaml
