apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-admin-api
  labels:
    app: treetracker-admin-api
spec:
  template:
    spec:
      containers:
        - name: treetracker-admin-api
          env:
            - name: ENABLE_VERIFY_PUBLISHING
              value: 'true'
