apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: treetracker-rabbitmq-connection
  namespace: development
spec:
  encryptedData:
    messageQueue: AgCBna7t8jy6TYM4+3KdZMelX5U95LN9n0/OJOUZ1FNlHn255ekFX4iNRmZiR0TTHGqGyqSb27IGgyenZi6TyJS1ciu9zN8HEznirwFF483+jl0T+HgtmFEP5qZ7T192++A4BHUQGMXrqahztUDO/dLBjeG0AgL+nYiEkIBGDgBvD38sSZvQBZSiBmlaReDElW+crh4pifQ/WWsvfwqq+/MeDEPusw4wa0itY3FUYp3rTj7/qBOgCe1wk8UNw3/wha39LiSPHGzxkMfCOYFf+3z9ADfq16MfzYcbXzVDChF8WycIa7hg4+h7Jo+RvtcqCBiyuyRokK4PPFh1rExiy772m7jvAoXmmeNZozkSVx/U99UY9YWSMDw2TMtiwlDP+y/lo12N0aoxn3yKnmozytk7IQycA2RoAnicY4XKM50UPN270x7WhRwR8STir7Zq1hfOfIeVIgSZ8hiZL/6krL5BxrnDib9GWIQ5OSQZVrrZTrPuEYRLeIS/JI1jSSCFGnpDHLhRWczUZn92CR8dgy1+ExiZlGlc5YIby5TBAR6QzrqyZ8su0FSAxHc7jZLg0jp5XhVljdBU8ot7wtmmUfYoq/Oohh3w3Wg/Uo1K+/QcRNyv10l/H2JVUzzodh1vSU4cJGYjArKiBovDrAQoctw0TpoOT3ZeyfvA9lScuLl4+g+V+ZZUJiykhxDvIOKcx1o3Inz7WPcS/S8VmgWTFq/p2ztOgSspYmaRTgLk9vJZ4bmX6hq7RO2qELxNy1yXZhyxeyA04shqqggdFzTYBpmV/lbKPhi79Swzc96mz7OVkwPMnajUYw==
  template:
    metadata:
      name: treetracker-rabbitmq-connection
      namespace: development
