# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Admin Panel CI/CD Pipeline

on:
  push:
    branches:
      # - master. Recommiting appears to solve problem of triggering workflow.
      - Urey_GitHub_Actions
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    name: build Client Side of Admin Panel
    runs-on: ubuntu-latest

    # To consider in the future: build with several versions of node
    
    # Use node version 12.x
    steps:
    # Required for workflow
    - uses: actions/checkout@v2
      with: 
        repository: uchan3/treetracker-admin/client
        
    # Takes Node.js version and configures for runner
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci #For installing versions specific to package-lock.json
    - run: npm run build --if-present
    - run: npm test